- title: "The Value Creator Playbook"
  description: "Write genius ideas that cause people to take action and win you followers who care about what you offer."
  image: "value-book.png"
  alt: "The Value Creator Playbook"
  button_text: "Get The Book"
  link: "https://nas.io/skillembassy/tusf"

- title: "Micro Reading Hub"
  description: "If you don't improve your mind, you cannot improve your life. Choosing a book over mindless entertainment and self-deprecating memes is self-discipline."
  image: "book-hub.png"
  alt: "Micro Reading Hub"
  button_text: "Grab A Copy"
  link: "https://nas.io/skillembassy/kpsv"

- title: "Ideas to Profit"
  description: "Come and learn how to monetize your creative skills. Launch an online business with real customers and your own cross-disciplinary team."
  image: "microbusiness.png"
  alt: "Ideas to Profit"
  button_text: "Get Early Access"
  link: "https://nas.io/checkout-global?communityId=63cca6ba6b6b7d12431df1eb&communityCode=CAREERS_IN_TECH&requestor=whatsappSignup&sourceInfoType=folder&sourceInfoOrigin=65be06725d542ebc015ba2b9"
